# Change these first
owner: lodinesoftware # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: Website
    url: https://lodine.xyz
    icon: https://raw.githubusercontent.com/lodinesoftware/uptime/refs/heads/master/assets/lodine.png
  - name: Content Delivery Network
    url: https://cdn.lodine.xyz
    icon: https://raw.githubusercontent.com/lodinesoftware/uptime/refs/heads/master/assets/lodine.png
    expectedStatusCodes:
      - 404

status-website:
  cname: status.lodine.xyz
  logoUrl: https://raw.githubusercontent.com/lodinesoftware/uptime/refs/heads/master/assets/lodine.png
  favicon: https://raw.githubusercontent.com/lodinesoftware/uptime/refs/heads/master/assets/lodine.png
  name: Lodine Services Uptime
  introTitle: "Official status page for our projects and services."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
